nro1 = int(input("Ing. el 1er. número"))
nro2 = int(input("Ing. el 2do. número"))
print("La suma es: ", nro1 + nro2)
print("La rest es: ", nro1 - nro2)
print("La multiplicación es: ", nro1 * nro2)
print("La división decimal es: ", nro1 / nro2)
print("La división entera es: ", nro1 // nro2)
print("El residuo es: ", nro1 % nro2)
